services:
  context.customer.controller.customerController:
    class: App\Customer\Controller\CustomerController
    arguments: [
      "@context.customer.application.customerApplication"
    ]

  context.customer.application.customerApplication:
    class: App\Customer\Application\CustomerApplication
    arguments: [
      "@context.customer.domain.service.customerService"
    ]

  context.customer.domain.service.customerService:
    class: App\Customer\Domain\Service\CustomerService